#!/bin/sh
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -j gnuob-order-service-1.0.jar -b gnuob-order-service-binding.xml --output /home/bernard/workspace/gnuob-app/src/main/webapp/WEB-INF/lib http://localhost:8080/gnuob-soap/OrderWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -j gnuob-product-service-1.0.jar -b gnuob-product-service-binding.xml --output /home/bernard/workspace/gnuob-app/src/main/webapp/WEB-INF/lib http://localhost:8080/gnuob-soap/ProductWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -j gnuob-paypal-service-1.0.jar -b gnuob-paypal-service-binding.xml --output /home/bernard/workspace/gnuob-app/src/main/webapp/WEB-INF/lib http://localhost:8080/gnuob-soap/PayPalExpressCheckOutWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -j gnuob-category-service-1.0.jar -b gnuob-category-service-binding.xml --output /home/bernard/workspace/gnuob-app/src/main/webapp/WEB-INF/lib http://localhost:8080/gnuob-soap/CategoryWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -j gnuob-content-service-1.0.jar -b gnuob-content-service-binding.xml --output /home/bernard/workspace/gnuob-app/src/main/webapp/WEB-INF/lib http://localhost:8080/gnuob-soap/ContentWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -j gnuob-contract-service-1.0.jar -b gnuob-contract-service-binding.xml --output /home/bernard/workspace/gnuob-app/src/main/webapp/WEB-INF/lib http://localhost:8080/gnuob-soap/ContractWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -j gnuob-customer-service-1.0.jar -b gnuob-customer-service-binding.xml --output /home/bernard/workspace/gnuob-app/src/main/webapp/WEB-INF/lib http://localhost:8080/gnuob-soap/CustomerWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -j gnuob-offer-service-1.0.jar -b gnuob-offer-service-binding.xml --output /home/bernard/workspace/gnuob-app/src/main/webapp/WEB-INF/lib http://localhost:8080/gnuob-soap/OfferWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -j gnuob-user-service-1.0.jar -b gnuob-user-service-binding.xml --output /home/bernard/workspace/gnuob-app/src/main/webapp/WEB-INF/lib http://localhost:8080/gnuob-soap/UserWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -j gnuob-group-service-1.0.jar -b gnuob-group-service-binding.xml --output /home/bernard/workspace/gnuob-app/src/main/webapp/WEB-INF/lib http://localhost:8080/gnuob-soap/GroupWebServiceImpl?wsdl
/home/bernard/Tools/wildfly-8.1.0.Final/bin/wsconsume.sh -j gnuob-site-service-1.0.jar -b gnuob-site-service-binding.xml --output /home/bernard/workspace/gnuob-app/src/main/webapp/WEB-INF/lib http://localhost:8080/gnuob-soap/SiteWebServiceImpl?wsdl
